# Generated by Django 3.1 on 2022-02-03 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent', to='main.autopost')),
                ('renter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
