# Generated by Django 3.1 on 2022-02-03 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rating_ratingstar'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopost',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='main.autopost', verbose_name='авто'),
        ),
    ]
