# Generated by Django 3.1 on 2022-02-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220203_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ip',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ratingstar',
            name='value',
            field=models.SmallIntegerField(default=0),
        ),
    ]
