# Generated by Django 3.1 on 2022-02-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopost',
            name='middle_star',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='autopost',
            name='rating_user',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
