# Generated by Django 3.1 on 2022-02-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220204_0636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
