# Generated by Django 3.1 on 2022-02-04 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autopost',
            name='middle_star',
        ),
        migrations.RemoveField(
            model_name='autopost',
            name='rating_user',
        ),
    ]
