# Generated by Django 3.1 on 2022-02-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220204_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autopost',
            name='middle_star',
        ),
        migrations.RemoveField(
            model_name='autopost',
            name='rating_user',
        ),
    ]
